apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: juanlopezaranzazu388/ds3-users-service:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: EUREKA_SERVER_HOST
              value: "eureka-service"
            - name: EUREKA_SERVER_PORT
              value: "8761"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: JWT_SECRET
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: EMAIL_USERNAME
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: EMAIL_PASSWORD
            - name: FRONTEND_RESET_PASSWORD_URL
              value: "http://localhost:30081/api/v1/auth/reset-password"
